;
; File generated by cc65 v 2.19 - Git 93c1b659e
;
	.fopt		compiler,"cc65 v 2.19 - Git 93c1b659e"
	.setcpu		"65EL02"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	c_sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.forceimport	__STARTUP__
	.export		_main

; ---------------------------------------------------------------
; int __near__ main (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_main: near

.segment	"CODE"

	ldx     #$00
	lda     #$00
	jsr     pushax
	ldx     #$00
	lda     #$01
	jsr     pushax
	jmp     L0004
L0002:	ldy     #$03
	jsr     ldaxysp
	jsr     pushax
	ldy     #$03
	jsr     ldaxysp
	ldy     #$04
	jsr     staxysp
	ldy     #$03
	jsr     ldaxysp
	jsr     pushax
	ldy     #$03
	jsr     ldaxysp
	jsr     tosaddax
	ldy     #$02
	jsr     staxysp
	jsr     incsp2
L0004:	jmp     L0002
	rts

.endproc

